name: GitHub Artifact Demo

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # triggers on tags like v1.0.0, v2.1.3, etc.

jobs:
  artifact-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate artifact generation
        run: |
          mkdir build
          echo "Build completed at $(date)" > build/output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: build/
          retention-days: 30

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/output.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
