name: Artifact Demo

on:
  push:
    tags:
      - 'v*.*.*'   # Runs only when a tag like v1.0.0 is pushed

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Artifact
        run: |
          mkdir -p build
          echo "This is the build output" > build/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: build/output.txt
          retention-days: 30

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/output.txt
          token: ${{ secrets.PAT_TOKEN }}
